# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc6c58ff0afc1d996898a6ebe4bedce4100bdbb338e574dfd4b2c82412e604ebf465832a6060c1eb2577e59d1193dc082e633f833b41cab2d8ea8ee6610c920a

test:
  secret_key_base: 4ac3e8bff9b500c901cec942dff7f7ce819b3737e3d0da8693decba571ce889d19aecd250af049695e0d992d658d4299a7fb90e9578d5ae04d11b3b589506262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
